### ISSUE TITLE
Test suite breaks on lookahead grammar.

### ISSUE THREAD

**Issue by pouyakary** [dart-lang/dart-syntax-highlight#32]
So I tried to add more tests to the suite written by @DanTup, the problem is the test breaks:

```
✶ ~/Developer/dart-syntax-highlight ✶ dart run test
Building package executable... (2.8s)
Built test:test.
00:00 +0 -1: loading test/golden_test.dart [E]                                                                                  
  Failed to load "test/golden_test.dart": Invalid group(?>!(?:await|return)\s+)([_$]*[a-z][a-zA-Z0-9_$]*)\s+([_$]*[a-z][a-zA-Z0-9_$]*)\s*(<(?:[a-zA-Z0-9_$<>?]|,\s*|\s+extends\s+)+>)?\s*[!?]?\s*(\(|\s+=>)
  dart:core                             new RegExp
  test/support/span_parser.dart 258:17  new _SimpleMatcher
  test/support/span_parser.dart 194:14  new _Matcher.parse
  test/support/span_parser.dart 175:36  new Repository.build
  test/support/span_parser.dart 51:30   new Grammar.fromJson
  test/golden_test.dart 18:27           main
  

To run this test again: /Applications/flutter/bin/cache/dart-sdk/bin/dart test test/golden_test.dart -p vm --plain-name 'loading test/golden_test.dart'
00:00 +0 -1: Some tests failed.       
```

I think it's probably because of [Oniguruma](https://github.com/kkos/oniguruma)'s special lookahead not supported by the test suite. Is that right?

**Comment by DanTup** [comment]
> I think it's probably because of [Oniguruma](https://github.com/kkos/oniguruma)'s special lookahead not supported by the test suite. Is that right?

I'm not familiar with Oniguruma, but if that's special syntax not supported by the Dart RegExp class then that sounds plausible. Is it possible to tweak it to be in a form that the [Dart RegExp class](https://api.dart.dev/stable/2.18.2/dart-core/RegExp-class.html) can parse?

**Comment by devoncarew** [comment]
Some additional context at https://github.com/dart-lang/dart-syntax-highlight/pull/40.

**Comment by devoncarew** [comment]
Is this an actual issue? Do we see this problem in VS Code? In the github syntax highlighter? I'm trying to better understand the issue here and the impact to users.

**Comment by pouyakary** [comment]
@devoncarew yeah it's actually a massive problem on my side. My theme looks really bad on Dart and that is because I cannot style my theme to match Dart. So I had to fix things one by one (all of which I have documented in the issue). I'm on a crunch in my company that's kinda taking around a 4 months now and so I couldn't have put the time to migrate the changes here. But it actually is real and big. I have matched my theme to around 40 languages now, some of which required me to either contribute to the language syntax or develop the grammar for them, and by comparison this is the biggest one in my side. While I'm unfortunately still not able to bring the changes to the main dart grammar, I'm happy and available to answer any questions you have. Ping me anytime.

**Comment by DanTup** [comment]
@pouyakary are you able to give an example of some code that doesn't work correctly with the existing grammar that requires this? The PR had a lot of changes and it wasn't clear to me why this syntax was required so it was hard to try to find an alternative (I also wasn't able to find a good description of this syntax - see https://github.com/dart-lang/dart-syntax-highlight/pull/40#discussion_r1108617666).

I'm happy to try to fix things that aren't working with your theme, but you might need to provide some code samples that aren't working correctly for me to debug. The original change was quite large and done before there was proper testing here. Now that there is, we should ensure each change has a relevant code snippet in the tests so that future changes can't regress the fixes.

**Comment by pouyakary** [comment]
@DanTup yeah I would love to do that. The biggest change that I brought to the grammar was that __*"any token should have its own rule"*__. These are two versions of VS Code with the normal grammar on the left, and my changes on the right:

<img src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/4b612eca-b2c5-4ce2-b88c-feacf953f870">

The rule of thumb on my theme is that identifiers should be blue, everything else has their own colors and punctuations are black. To achieve this I had to color everything blue and then color specific tokens, and all punctuations so that anything that remains blue be the identifiers. Problem with the current grammar is that there are places where there is no differentiation between tokens. Some keywords and grammars have colors but not all. I wanted everything to have their own tag. Look at this example:

<img src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/7e30a3da-1724-45d4-8d31-af6dbb19dc28">

in the original grammar only the `get` word is defined as a keyword (and only as a keyword) everything else is plain source code. My version defines the grammar so one can color any single token specifically and achieve the look that my theme needs. Not only that but each keyword for example has its own name in it, so you can specifically color the `get` keyword different than other keywords if you like to.

<img src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/9bcdbfbe-a102-4e9a-9133-cdb161ee1528">

And there are many parts that you may not notice, but for example, in the original version there is a generic class definition that detect identifiers that start with uppercase letters. This generic parameter is detected as a class, my version specifically defines it as a generic parameter:

<img src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/0f39ed0f-7fe9-4575-b636-dc8c4c7124b5">

<img src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/3fdb8cb5-667b-47fd-8a4e-2ed351f14941">

I don't remember all of the changes since they are many, but I guess you get the gist of it. Every token having specific scopes tagged to them so that you can theme with the highest precision possible and have the most consistent look that one can get.

**Comment by DanTup** [comment]
@pouyakary is there a reason you're not supporting Semantic Tokens in your theme? I think many of the things you're trying to handle here may already be supported there. We have a number of custom modifiers applied to semantic tokens where there have been requests to provide better syntax highlighting.

The advantage with semantic tokens is that it comes from the Dart analysis server, so it's always accurate (we're not trying to parse code with regex) and it always matches the language version the user is using (whereas the textmate grammar is fixed by the installed version of the extension).

**Comment by pouyakary** [comment]
@DanTup @devoncarew

Sorry for the late reply. I had to test your words and come back with data. I didn't use the semantic colors in my theme. I updated my theme (which was a little bit hard since I needed to update my theme compiler). So many things seems good but there are some missing:

- All punctuations are missing scopes <br><br> <img width="771"  src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/2c7dd0c6-0f83-4fab-8b35-9d265ecbfa2b">

- Object property keys are not colored <br><br> <img width="643" src="https://github.com/dart-lang/dart-syntax-highlight/assets/2157285/1de1053b-22b9-4a49-8d17-d34462e82453">

I guess everything else looks good and I can patch these two quickly in PRs.

What I wanted was a full featured syntax file that if you brought it to say Sublime then it looked exactly the same as vscode without the use of extensions. but this looks really good and is a lot smarter and better. So I guess we can ignore those works (I'll still maintain it somewhere else) and patch the current grammar for these things.

**Comment by pouyakary** [comment]
And with that lets close the PR (but continue the conversation if you wanted)

**Comment by DanTup** [comment]
Glad to hear the semantic tokens solve many of the issues!

If you want to send PRs to fix those remaining things here that would be great. We should ensure that those changes do not conflict with semantic tokens though, so if you add scopes for named arguments so they can be themed, we should ensure the semantic tokens do not overwrite/undo them. If the semantic tokens don't already have a custom modifier for those, we can add one so that it's possible to apply the color customization both to the grammar and semantic token.
